const { test } = require('node:test');
const assert = require('node:assert/strict');
const { chromium } = require('playwright');

test('Studio restores navigation and keeps production folders usable', async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
  const base = process.env.LAB_TEST_URL || 'http://127.0.0.1:8765';
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.route('**/api/comfy/**', (route) => route.fulfill({ json: { connected: false, jobs: [], summary: {} } }));
  await page.route('**/api/agent/config*', (route) => route.fulfill({ json: { configured: false } }));
  try {
    await page.goto(base + '/');
    const data = await page.evaluate(async () => (await fetch('/api/catalog')).json());
    const story = data.stories.find((item) => item.episodes.length >= 2);
    const other = data.stories.find((item) => item.id !== story.id && item.episodes.some((episode) => episode.references.length));
    const episode = story.episodes[1];
    const clip = episode.clips[1];
    const storyButton = (id) => `[data-action="select-story"][data-story="${id}"]`;
    const episodeButton = (sid, eid) => `[data-action="select-episode"][data-story="${sid}"][data-episode="${eid}"]`;
    await page.locator(storyButton(story.id)).click();
    await page.locator(episodeButton(story.id, episode.id)).click();
    await page.locator(`[data-action="select-clip"][data-story="${story.id}"][data-episode="${episode.id}"][data-clip="${clip.id}"]`).click();
    await page.locator('[data-tab="prompt"]').click();
    await page.evaluate(() => { document.querySelector('.workspace').scrollTop = 300; });
    await page.waitForFunction(() => JSON.parse(localStorage.getItem('aiturboshow.studio.navigation.v1')).viewPositions[`${state.storyId}:${state.episodeId}`]?.workspace === 300);
    await page.reload();
    await page.waitForSelector('[data-tab="prompt"].active');
    assert.equal(await page.locator('#inspectorTitle').textContent(), clip.title);
    assert.equal(await page.evaluate(() => document.querySelector('.workspace').scrollTop), 300);
    await page.locator(storyButton(other.id)).click();
    await page.locator(storyButton(story.id)).click();
    assert.equal(await page.locator(episodeButton(story.id, episode.id)).getAttribute('aria-current'), 'location');
    await page.locator('#collapseProductions').click();
    await page.reload();
    await page.waitForSelector('[data-tree-toggle="story"]');
    assert.equal(await page.locator('[data-tree-toggle="story"][aria-expanded="true"]').count(), 0);
    await page.locator('#revealProduction').click();
    assert.equal(await page.locator(episodeButton(story.id, episode.id)).isVisible(), true);
    const toggle = page.locator(`[data-tree-toggle="episode"][data-story="${story.id}"][data-episode="${episode.id}"]`);
    await toggle.focus();
    await page.keyboard.press('Space');
    assert.equal(await toggle.getAttribute('aria-expanded'), 'false');
    assert.equal(await toggle.evaluate((button) => button === document.activeElement), true);
    await page.fill('#searchInput', clip.title);
    assert.equal(await page.locator(`[data-action="select-clip"][data-story="${story.id}"][data-episode="${episode.id}"][data-clip="${clip.id}"]`).isVisible(), true);
    await page.fill('#searchInput', '');
    assert.equal(await toggle.getAttribute('aria-expanded'), 'false');
    await page.locator(storyButton(other.id)).click();
    const referenceEpisode = other.episodes.find((item) => item.references.length);
    await page.locator(episodeButton(other.id, referenceEpisode.id)).click();
    await page.locator('#episodeReferences [data-reference]').first().click();
    const referenceTitle = await page.locator('#inspectorTitle').textContent();
    await page.locator('[data-tab="prompt"]').click();
    await page.reload();
    await page.waitForSelector('[data-tab="prompt"].active');
    assert.equal(await page.locator('#inspectorTitle').textContent(), referenceTitle);
    assert.equal(await page.locator('.tree-branch-heading button button').count(), 0);
    await page.evaluate(() => localStorage.setItem('aiturboshow.studio.navigation.v1', JSON.stringify({ storyId: 'removed', episodeId: 'removed', selection: { type: 'clip', storyId: 'removed', clipId: 'removed' } })));
    await page.reload();
    await page.waitForSelector('[data-action="select-story"].active');
    assert.equal(await page.locator('#inspectorEmpty').isVisible(), true);
    await page.evaluate(() => localStorage.setItem('aiturboshow.studio.navigation.v1', '{corrupt'));
    await page.reload();
    await page.waitForSelector('[data-action="select-story"].active');
    assert.deepEqual(errors, []);
  } finally { await browser.close(); }
});
